#!/bin/sh

HOSTS="alpha beta"
SQUID=192.168.255.201:3128


if [ "x-f" == "x$1" ]; then
    FULL=1
fi

for i in ${HOSTS} ; do
    ssh -t $i 'pf-table add white $REMOTEHOST'
    case $i in
        alpha)
            ssh -t $i tmux new-session "freeupsomespace"
            ssh -t $i "env SQUID=10.7.7.1:3128 setproxy"
            if [ "1" == "$FULL" ]; then
                ssh -t $i tmux new-session "env PAGER=cat freebsd-update -F fetch install"
            fi
            ssh -t $i tmux new-session "fres"
            #ssh -t $i tmux new-session "env HTTP_PROXY=http://10.7.7.1:3128 eza-freebsd-update"
            ;;
        beta)
            ssh -t $i tmux new-session "freeupsomespace"
            ssh -t $i "env SQUID=${SQUID} setproxy"
            if [ "1" == "$FULL" ]; then
                ssh -t $i tmux new-session "env PAGER=cat freebsd-update -F fetch install"
            fi
            ssh -t $i tmux new-session "fres"
            #ssh -t $i tmux new-session "env HTTP_PROXY=http://${SQUID} eza-freebsd-update"
            ;;
        tank)
            ssh -t $i tmux new-session "freeupsomespace"
            ssh -t $i "env SQUID=${SQUID} setproxy"
            if [ "1" == "$FULL" ]; then
                ssh -t $i tmux new-session "env PAGER=cat freebsd-update -F fetch install"
            fi
            ssh -t $i tmux new-session "fres"
            ;;
        old)
            ssh -t $i tmux new-session "freeupsomespace"
            if [ "1" == "$FULL" ]; then
                ssh -t $i tmux new-session "env PAGER=cat freebsd-update -F fetch install"
            fi
            ssh -t $i tmux new-session "fres"
            ;;
    esac
    ssh -t $i 'pf-table remove white $REMOTEHOST'
    ssh $i 'pf-table save all'
done
